//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.LOGIN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LOGIN.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerTerminalesDisponibles", ReplyAction="http://tempuri.org/IService/ObtenerTerminalesDisponiblesResponse")]
        System.Data.DataSet ObtenerTerminalesDisponibles(string StrCodigo, string StrUsuarioAdmin, string StrPasswordAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerTerminalesDisponibles", ReplyAction="http://tempuri.org/IService/ObtenerTerminalesDisponiblesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTerminalesDisponiblesAsync(string StrCodigo, string StrUsuarioAdmin, string StrPasswordAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConfigurarTerminal", ReplyAction="http://tempuri.org/IService/ConfigurarTerminalResponse")]
        string ConfigurarTerminal(string StrAgencia, string StrRemoteIp, string StrRemoteHost, string StrUsuario, string StrConnectorId, string StrTerminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConfigurarTerminal", ReplyAction="http://tempuri.org/IService/ConfigurarTerminalResponse")]
        System.Threading.Tasks.Task<string> ConfigurarTerminalAsync(string StrAgencia, string StrRemoteIp, string StrRemoteHost, string StrUsuario, string StrConnectorId, string StrTerminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTerminalByConnectorID", ReplyAction="http://tempuri.org/IService/GetTerminalByConnectorIDResponse")]
        WebApplication1.LOGIN.GetTerminalByConnectorIDResponse GetTerminalByConnectorID(WebApplication1.LOGIN.GetTerminalByConnectorIDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTerminalByConnectorID", ReplyAction="http://tempuri.org/IService/GetTerminalByConnectorIDResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.GetTerminalByConnectorIDResponse> GetTerminalByConnectorIDAsync(WebApplication1.LOGIN.GetTerminalByConnectorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTerminalSegByConnectorID", ReplyAction="http://tempuri.org/IService/GetTerminalSegByConnectorIDResponse")]
        WebApplication1.LOGIN.GetTerminalSegByConnectorIDResponse GetTerminalSegByConnectorID(WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTerminalSegByConnectorID", ReplyAction="http://tempuri.org/IService/GetTerminalSegByConnectorIDResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.GetTerminalSegByConnectorIDResponse> GetTerminalSegByConnectorIDAsync(WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConfigurarTerminalSeguridad", ReplyAction="http://tempuri.org/IService/ConfigurarTerminalSeguridadResponse")]
        string ConfigurarTerminalSeguridad(string ConnectorID, string DataTimeConfig, string BrowserType, string BrowserName, string OSPlataform, string ComputerID, string IpAddress, string User_Session, string MAC_Address, string OperationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConfigurarTerminalSeguridad", ReplyAction="http://tempuri.org/IService/ConfigurarTerminalSeguridadResponse")]
        System.Threading.Tasks.Task<string> ConfigurarTerminalSeguridadAsync(string ConnectorID, string DataTimeConfig, string BrowserType, string BrowserName, string OSPlataform, string ComputerID, string IpAddress, string User_Session, string MAC_Address, string OperationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        WebApplication1.LOGIN.LoginResponse Login(WebApplication1.LOGIN.LoginRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.LoginResponse> LoginAsync(WebApplication1.LOGIN.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginHuella", ReplyAction="http://tempuri.org/IService/LoginHuellaResponse")]
        WebApplication1.LOGIN.LoginHuellaResponse LoginHuella(WebApplication1.LOGIN.LoginHuellaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginHuella", ReplyAction="http://tempuri.org/IService/LoginHuellaResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.LoginHuellaResponse> LoginHuellaAsync(WebApplication1.LOGIN.LoginHuellaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PasswordChangeLogin", ReplyAction="http://tempuri.org/IService/PasswordChangeLoginResponse")]
        WebApplication1.LOGIN.PasswordChangeLoginResponse PasswordChangeLogin(WebApplication1.LOGIN.PasswordChangeLoginRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PasswordChangeLogin", ReplyAction="http://tempuri.org/IService/PasswordChangeLoginResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.PasswordChangeLoginResponse> PasswordChangeLoginAsync(WebApplication1.LOGIN.PasswordChangeLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PasswordChange", ReplyAction="http://tempuri.org/IService/PasswordChangeResponse")]
        WebApplication1.LOGIN.PasswordChangeResponse PasswordChange(WebApplication1.LOGIN.PasswordChangeRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PasswordChange", ReplyAction="http://tempuri.org/IService/PasswordChangeResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.PasswordChangeResponse> PasswordChangeAsync(WebApplication1.LOGIN.PasswordChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Logout", ReplyAction="http://tempuri.org/IService/LogoutResponse")]
        void Logout(string StrCodigo, string StrUsuario, string StrPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Logout", ReplyAction="http://tempuri.org/IService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string StrCodigo, string StrUsuario, string StrPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StoreLoginInfo", ReplyAction="http://tempuri.org/IService/StoreLoginInfoResponse")]
        void StoreLoginInfo(string ConnectorID, string RemoteIP, string BrowserType, string BrowerPlataform, string DataTimeConfig, string BrowserName, string ComputerID, string OperationID, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StoreLoginInfo", ReplyAction="http://tempuri.org/IService/StoreLoginInfoResponse")]
        System.Threading.Tasks.Task StoreLoginInfoAsync(string ConnectorID, string RemoteIP, string BrowserType, string BrowerPlataform, string DataTimeConfig, string BrowserName, string ComputerID, string OperationID, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUserReference", ReplyAction="http://tempuri.org/IService/CreateUserReferenceResponse")]
        WebApplication1.LOGIN.CreateUserReferenceResponse CreateUserReference(WebApplication1.LOGIN.CreateUserReferenceRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUserReference", ReplyAction="http://tempuri.org/IService/CreateUserReferenceResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.CreateUserReferenceResponse> CreateUserReferenceAsync(WebApplication1.LOGIN.CreateUserReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalHuella", ReplyAction="http://tempuri.org/IService/TerminalHuellaResponse")]
        WebApplication1.LOGIN.TerminalHuellaResponse TerminalHuella(WebApplication1.LOGIN.TerminalHuellaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalHuella", ReplyAction="http://tempuri.org/IService/TerminalHuellaResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.TerminalHuellaResponse> TerminalHuellaAsync(WebApplication1.LOGIN.TerminalHuellaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalConfigurada", ReplyAction="http://tempuri.org/IService/TerminalConfiguradaResponse")]
        bool TerminalConfigurada(string usuarioConfigurador, string Terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalConfigurada", ReplyAction="http://tempuri.org/IService/TerminalConfiguradaResponse")]
        System.Threading.Tasks.Task<bool> TerminalConfiguradaAsync(string usuarioConfigurador, string Terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalReseteada", ReplyAction="http://tempuri.org/IService/TerminalReseteadaResponse")]
        bool TerminalReseteada();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TerminalReseteada", ReplyAction="http://tempuri.org/IService/TerminalReseteadaResponse")]
        System.Threading.Tasks.Task<bool> TerminalReseteadaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarHuella", ReplyAction="http://tempuri.org/IService/ValidarHuellaResponse")]
        WebApplication1.LOGIN.ValidarHuellaResponse ValidarHuella(WebApplication1.LOGIN.ValidarHuellaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarHuella", ReplyAction="http://tempuri.org/IService/ValidarHuellaResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.ValidarHuellaResponse> ValidarHuellaAsync(WebApplication1.LOGIN.ValidarHuellaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarLogin", ReplyAction="http://tempuri.org/IService/ValidarLoginResponse")]
        WebApplication1.LOGIN.ValidarLoginResponse ValidarLogin(WebApplication1.LOGIN.ValidarLoginRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarLogin", ReplyAction="http://tempuri.org/IService/ValidarLoginResponse")]
        System.Threading.Tasks.Task<WebApplication1.LOGIN.ValidarLoginResponse> ValidarLoginAsync(WebApplication1.LOGIN.ValidarLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminalByConnectorID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminalByConnectorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ConnectorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public GetTerminalByConnectorIDRequest() {
        }
        
        public GetTerminalByConnectorIDRequest(string ConnectorId, System.Data.DataTable Data, string StrError) {
            this.ConnectorId = ConnectorId;
            this.Data = Data;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminalByConnectorIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminalByConnectorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetTerminalByConnectorIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public GetTerminalByConnectorIDResponse() {
        }
        
        public GetTerminalByConnectorIDResponse(bool GetTerminalByConnectorIDResult, System.Data.DataTable Data, string StrError) {
            this.GetTerminalByConnectorIDResult = GetTerminalByConnectorIDResult;
            this.Data = Data;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminalSegByConnectorID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminalSegByConnectorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ConnectorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public GetTerminalSegByConnectorIDRequest() {
        }
        
        public GetTerminalSegByConnectorIDRequest(string ConnectorId, System.Data.DataTable Data, string StrError) {
            this.ConnectorId = ConnectorId;
            this.Data = Data;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTerminalSegByConnectorIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTerminalSegByConnectorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetTerminalSegByConnectorIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public GetTerminalSegByConnectorIDResponse() {
        }
        
        public GetTerminalSegByConnectorIDResponse(bool GetTerminalSegByConnectorIDResult, System.Data.DataTable Data, string StrError) {
            this.GetTerminalSegByConnectorIDResult = GetTerminalSegByConnectorIDResult;
            this.Data = Data;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool BolChangePass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string StrError;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string StrCodigo, string StrUsuario, string StrPassword, System.Data.DataTable DataUser, bool BolChangePass, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.StrPassword = StrPassword;
            this.DataUser = DataUser;
            this.BolChangePass = BolChangePass;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool BolChangePass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrError;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool LoginResult, System.Data.DataTable DataUser, bool BolChangePass, string StrError) {
            this.LoginResult = LoginResult;
            this.DataUser = DataUser;
            this.BolChangePass = BolChangePass;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginHuella", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginHuellaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pFMD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string StrError;
        
        public LoginHuellaRequest() {
        }
        
        public LoginHuellaRequest(string StrCodigo, string StrUsuario, string pFMD, System.Data.DataTable DataUser, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.pFMD = pFMD;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginHuellaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginHuellaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginHuellaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public LoginHuellaResponse() {
        }
        
        public LoginHuellaResponse(bool LoginHuellaResult, System.Data.DataTable DataUser, string StrError) {
            this.LoginHuellaResult = LoginHuellaResult;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PasswordChangeLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PasswordChangeLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrOldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrNewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string IntSecLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string StrError;
        
        public PasswordChangeLoginRequest() {
        }
        
        public PasswordChangeLoginRequest(string StrCodigo, string StrUsuario, string StrOldPassword, string StrNewPassword, string IntSecLevel, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.StrOldPassword = StrOldPassword;
            this.StrNewPassword = StrNewPassword;
            this.IntSecLevel = IntSecLevel;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PasswordChangeLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PasswordChangeLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PasswordChangeLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrError;
        
        public PasswordChangeLoginResponse() {
        }
        
        public PasswordChangeLoginResponse(bool PasswordChangeLoginResult, string StrError) {
            this.PasswordChangeLoginResult = PasswordChangeLoginResult;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PasswordChange", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PasswordChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrOldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrNewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string IntSecLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string StrError;
        
        public PasswordChangeRequest() {
        }
        
        public PasswordChangeRequest(string StrCodigo, string StrUsuario, string StrOldPassword, string StrNewPassword, string IntSecLevel, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.StrOldPassword = StrOldPassword;
            this.StrNewPassword = StrNewPassword;
            this.IntSecLevel = IntSecLevel;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PasswordChangeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PasswordChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PasswordChangeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrError;
        
        public PasswordChangeResponse() {
        }
        
        public PasswordChangeResponse(bool PasswordChangeResult, string StrError) {
            this.PasswordChangeResult = PasswordChangeResult;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserReference", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserReferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pServicePointID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pConfServicePointID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pConfUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pReferenceData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string rError;
        
        public CreateUserReferenceRequest() {
        }
        
        public CreateUserReferenceRequest(int pServicePointID, string pUserID, int pConfServicePointID, string pConfUserID, string pReferenceData, string rError) {
            this.pServicePointID = pServicePointID;
            this.pUserID = pUserID;
            this.pConfServicePointID = pConfServicePointID;
            this.pConfUserID = pConfUserID;
            this.pReferenceData = pReferenceData;
            this.rError = rError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserReferenceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateUserReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string rError;
        
        public CreateUserReferenceResponse() {
        }
        
        public CreateUserReferenceResponse(bool CreateUserReferenceResult, string rError) {
            this.CreateUserReferenceResult = CreateUserReferenceResult;
            this.rError = rError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminalHuella", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminalHuellaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pConnector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pError;
        
        public TerminalHuellaRequest() {
        }
        
        public TerminalHuellaRequest(string pConnector, string pError) {
            this.pConnector = pConnector;
            this.pError = pError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminalHuellaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminalHuellaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TerminalHuellaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pError;
        
        public TerminalHuellaResponse() {
        }
        
        public TerminalHuellaResponse(bool TerminalHuellaResult, string pError) {
            this.TerminalHuellaResult = TerminalHuellaResult;
            this.pError = pError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarHuella", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarHuellaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pFMD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string StrError;
        
        public ValidarHuellaRequest() {
        }
        
        public ValidarHuellaRequest(string StrCodigo, string StrUsuario, string pFMD, System.Data.DataTable DataUser, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.pFMD = pFMD;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarHuellaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarHuellaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidarHuellaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public ValidarHuellaResponse() {
        }
        
        public ValidarHuellaResponse(bool ValidarHuellaResult, System.Data.DataTable DataUser, string StrError) {
            this.ValidarHuellaResult = ValidarHuellaResult;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StrCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string StrUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pwd_Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string StrError;
        
        public ValidarLoginRequest() {
        }
        
        public ValidarLoginRequest(string StrCodigo, string StrUsuario, string pwd_Login, System.Data.DataTable DataUser, string StrError) {
            this.StrCodigo = StrCodigo;
            this.StrUsuario = StrUsuario;
            this.pwd_Login = pwd_Login;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidarLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable DataUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrError;
        
        public ValidarLoginResponse() {
        }
        
        public ValidarLoginResponse(bool ValidarLoginResult, System.Data.DataTable DataUser, string StrError) {
            this.ValidarLoginResult = ValidarLoginResult;
            this.DataUser = DataUser;
            this.StrError = StrError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplication1.LOGIN.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplication1.LOGIN.IService>, WebApplication1.LOGIN.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerTerminalesDisponibles(string StrCodigo, string StrUsuarioAdmin, string StrPasswordAdmin) {
            return base.Channel.ObtenerTerminalesDisponibles(StrCodigo, StrUsuarioAdmin, StrPasswordAdmin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTerminalesDisponiblesAsync(string StrCodigo, string StrUsuarioAdmin, string StrPasswordAdmin) {
            return base.Channel.ObtenerTerminalesDisponiblesAsync(StrCodigo, StrUsuarioAdmin, StrPasswordAdmin);
        }
        
        public string ConfigurarTerminal(string StrAgencia, string StrRemoteIp, string StrRemoteHost, string StrUsuario, string StrConnectorId, string StrTerminalId) {
            return base.Channel.ConfigurarTerminal(StrAgencia, StrRemoteIp, StrRemoteHost, StrUsuario, StrConnectorId, StrTerminalId);
        }
        
        public System.Threading.Tasks.Task<string> ConfigurarTerminalAsync(string StrAgencia, string StrRemoteIp, string StrRemoteHost, string StrUsuario, string StrConnectorId, string StrTerminalId) {
            return base.Channel.ConfigurarTerminalAsync(StrAgencia, StrRemoteIp, StrRemoteHost, StrUsuario, StrConnectorId, StrTerminalId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.GetTerminalByConnectorIDResponse WebApplication1.LOGIN.IService.GetTerminalByConnectorID(WebApplication1.LOGIN.GetTerminalByConnectorIDRequest request) {
            return base.Channel.GetTerminalByConnectorID(request);
        }
        
        public bool GetTerminalByConnectorID(string ConnectorId, ref System.Data.DataTable Data, ref string StrError) {
            WebApplication1.LOGIN.GetTerminalByConnectorIDRequest inValue = new WebApplication1.LOGIN.GetTerminalByConnectorIDRequest();
            inValue.ConnectorId = ConnectorId;
            inValue.Data = Data;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.GetTerminalByConnectorIDResponse retVal = ((WebApplication1.LOGIN.IService)(this)).GetTerminalByConnectorID(inValue);
            Data = retVal.Data;
            StrError = retVal.StrError;
            return retVal.GetTerminalByConnectorIDResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.GetTerminalByConnectorIDResponse> GetTerminalByConnectorIDAsync(WebApplication1.LOGIN.GetTerminalByConnectorIDRequest request) {
            return base.Channel.GetTerminalByConnectorIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.GetTerminalSegByConnectorIDResponse WebApplication1.LOGIN.IService.GetTerminalSegByConnectorID(WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest request) {
            return base.Channel.GetTerminalSegByConnectorID(request);
        }
        
        public bool GetTerminalSegByConnectorID(string ConnectorId, ref System.Data.DataTable Data, ref string StrError) {
            WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest inValue = new WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest();
            inValue.ConnectorId = ConnectorId;
            inValue.Data = Data;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.GetTerminalSegByConnectorIDResponse retVal = ((WebApplication1.LOGIN.IService)(this)).GetTerminalSegByConnectorID(inValue);
            Data = retVal.Data;
            StrError = retVal.StrError;
            return retVal.GetTerminalSegByConnectorIDResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.GetTerminalSegByConnectorIDResponse> GetTerminalSegByConnectorIDAsync(WebApplication1.LOGIN.GetTerminalSegByConnectorIDRequest request) {
            return base.Channel.GetTerminalSegByConnectorIDAsync(request);
        }
        
        public string ConfigurarTerminalSeguridad(string ConnectorID, string DataTimeConfig, string BrowserType, string BrowserName, string OSPlataform, string ComputerID, string IpAddress, string User_Session, string MAC_Address, string OperationID) {
            return base.Channel.ConfigurarTerminalSeguridad(ConnectorID, DataTimeConfig, BrowserType, BrowserName, OSPlataform, ComputerID, IpAddress, User_Session, MAC_Address, OperationID);
        }
        
        public System.Threading.Tasks.Task<string> ConfigurarTerminalSeguridadAsync(string ConnectorID, string DataTimeConfig, string BrowserType, string BrowserName, string OSPlataform, string ComputerID, string IpAddress, string User_Session, string MAC_Address, string OperationID) {
            return base.Channel.ConfigurarTerminalSeguridadAsync(ConnectorID, DataTimeConfig, BrowserType, BrowserName, OSPlataform, ComputerID, IpAddress, User_Session, MAC_Address, OperationID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.LoginResponse WebApplication1.LOGIN.IService.Login(WebApplication1.LOGIN.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string StrCodigo, string StrUsuario, string StrPassword, ref System.Data.DataTable DataUser, ref bool BolChangePass, ref string StrError) {
            WebApplication1.LOGIN.LoginRequest inValue = new WebApplication1.LOGIN.LoginRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.StrPassword = StrPassword;
            inValue.DataUser = DataUser;
            inValue.BolChangePass = BolChangePass;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.LoginResponse retVal = ((WebApplication1.LOGIN.IService)(this)).Login(inValue);
            DataUser = retVal.DataUser;
            BolChangePass = retVal.BolChangePass;
            StrError = retVal.StrError;
            return retVal.LoginResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.LoginResponse> LoginAsync(WebApplication1.LOGIN.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.LoginHuellaResponse WebApplication1.LOGIN.IService.LoginHuella(WebApplication1.LOGIN.LoginHuellaRequest request) {
            return base.Channel.LoginHuella(request);
        }
        
        public bool LoginHuella(string StrCodigo, string StrUsuario, string pFMD, ref System.Data.DataTable DataUser, ref string StrError) {
            WebApplication1.LOGIN.LoginHuellaRequest inValue = new WebApplication1.LOGIN.LoginHuellaRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.pFMD = pFMD;
            inValue.DataUser = DataUser;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.LoginHuellaResponse retVal = ((WebApplication1.LOGIN.IService)(this)).LoginHuella(inValue);
            DataUser = retVal.DataUser;
            StrError = retVal.StrError;
            return retVal.LoginHuellaResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.LoginHuellaResponse> LoginHuellaAsync(WebApplication1.LOGIN.LoginHuellaRequest request) {
            return base.Channel.LoginHuellaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.PasswordChangeLoginResponse WebApplication1.LOGIN.IService.PasswordChangeLogin(WebApplication1.LOGIN.PasswordChangeLoginRequest request) {
            return base.Channel.PasswordChangeLogin(request);
        }
        
        public bool PasswordChangeLogin(string StrCodigo, string StrUsuario, string StrOldPassword, string StrNewPassword, string IntSecLevel, ref string StrError) {
            WebApplication1.LOGIN.PasswordChangeLoginRequest inValue = new WebApplication1.LOGIN.PasswordChangeLoginRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.StrOldPassword = StrOldPassword;
            inValue.StrNewPassword = StrNewPassword;
            inValue.IntSecLevel = IntSecLevel;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.PasswordChangeLoginResponse retVal = ((WebApplication1.LOGIN.IService)(this)).PasswordChangeLogin(inValue);
            StrError = retVal.StrError;
            return retVal.PasswordChangeLoginResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.PasswordChangeLoginResponse> PasswordChangeLoginAsync(WebApplication1.LOGIN.PasswordChangeLoginRequest request) {
            return base.Channel.PasswordChangeLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.PasswordChangeResponse WebApplication1.LOGIN.IService.PasswordChange(WebApplication1.LOGIN.PasswordChangeRequest request) {
            return base.Channel.PasswordChange(request);
        }
        
        public bool PasswordChange(string StrCodigo, string StrUsuario, string StrOldPassword, string StrNewPassword, string IntSecLevel, ref string StrError) {
            WebApplication1.LOGIN.PasswordChangeRequest inValue = new WebApplication1.LOGIN.PasswordChangeRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.StrOldPassword = StrOldPassword;
            inValue.StrNewPassword = StrNewPassword;
            inValue.IntSecLevel = IntSecLevel;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.PasswordChangeResponse retVal = ((WebApplication1.LOGIN.IService)(this)).PasswordChange(inValue);
            StrError = retVal.StrError;
            return retVal.PasswordChangeResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.PasswordChangeResponse> PasswordChangeAsync(WebApplication1.LOGIN.PasswordChangeRequest request) {
            return base.Channel.PasswordChangeAsync(request);
        }
        
        public void Logout(string StrCodigo, string StrUsuario, string StrPassword) {
            base.Channel.Logout(StrCodigo, StrUsuario, StrPassword);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string StrCodigo, string StrUsuario, string StrPassword) {
            return base.Channel.LogoutAsync(StrCodigo, StrUsuario, StrPassword);
        }
        
        public void StoreLoginInfo(string ConnectorID, string RemoteIP, string BrowserType, string BrowerPlataform, string DataTimeConfig, string BrowserName, string ComputerID, string OperationID, string userid) {
            base.Channel.StoreLoginInfo(ConnectorID, RemoteIP, BrowserType, BrowerPlataform, DataTimeConfig, BrowserName, ComputerID, OperationID, userid);
        }
        
        public System.Threading.Tasks.Task StoreLoginInfoAsync(string ConnectorID, string RemoteIP, string BrowserType, string BrowerPlataform, string DataTimeConfig, string BrowserName, string ComputerID, string OperationID, string userid) {
            return base.Channel.StoreLoginInfoAsync(ConnectorID, RemoteIP, BrowserType, BrowerPlataform, DataTimeConfig, BrowserName, ComputerID, OperationID, userid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.CreateUserReferenceResponse WebApplication1.LOGIN.IService.CreateUserReference(WebApplication1.LOGIN.CreateUserReferenceRequest request) {
            return base.Channel.CreateUserReference(request);
        }
        
        public bool CreateUserReference(int pServicePointID, string pUserID, int pConfServicePointID, string pConfUserID, string pReferenceData, ref string rError) {
            WebApplication1.LOGIN.CreateUserReferenceRequest inValue = new WebApplication1.LOGIN.CreateUserReferenceRequest();
            inValue.pServicePointID = pServicePointID;
            inValue.pUserID = pUserID;
            inValue.pConfServicePointID = pConfServicePointID;
            inValue.pConfUserID = pConfUserID;
            inValue.pReferenceData = pReferenceData;
            inValue.rError = rError;
            WebApplication1.LOGIN.CreateUserReferenceResponse retVal = ((WebApplication1.LOGIN.IService)(this)).CreateUserReference(inValue);
            rError = retVal.rError;
            return retVal.CreateUserReferenceResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.CreateUserReferenceResponse> CreateUserReferenceAsync(WebApplication1.LOGIN.CreateUserReferenceRequest request) {
            return base.Channel.CreateUserReferenceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.TerminalHuellaResponse WebApplication1.LOGIN.IService.TerminalHuella(WebApplication1.LOGIN.TerminalHuellaRequest request) {
            return base.Channel.TerminalHuella(request);
        }
        
        public bool TerminalHuella(string pConnector, ref string pError) {
            WebApplication1.LOGIN.TerminalHuellaRequest inValue = new WebApplication1.LOGIN.TerminalHuellaRequest();
            inValue.pConnector = pConnector;
            inValue.pError = pError;
            WebApplication1.LOGIN.TerminalHuellaResponse retVal = ((WebApplication1.LOGIN.IService)(this)).TerminalHuella(inValue);
            pError = retVal.pError;
            return retVal.TerminalHuellaResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.TerminalHuellaResponse> TerminalHuellaAsync(WebApplication1.LOGIN.TerminalHuellaRequest request) {
            return base.Channel.TerminalHuellaAsync(request);
        }
        
        public bool TerminalConfigurada(string usuarioConfigurador, string Terminal) {
            return base.Channel.TerminalConfigurada(usuarioConfigurador, Terminal);
        }
        
        public System.Threading.Tasks.Task<bool> TerminalConfiguradaAsync(string usuarioConfigurador, string Terminal) {
            return base.Channel.TerminalConfiguradaAsync(usuarioConfigurador, Terminal);
        }
        
        public bool TerminalReseteada() {
            return base.Channel.TerminalReseteada();
        }
        
        public System.Threading.Tasks.Task<bool> TerminalReseteadaAsync() {
            return base.Channel.TerminalReseteadaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.ValidarHuellaResponse WebApplication1.LOGIN.IService.ValidarHuella(WebApplication1.LOGIN.ValidarHuellaRequest request) {
            return base.Channel.ValidarHuella(request);
        }
        
        public bool ValidarHuella(string StrCodigo, string StrUsuario, string pFMD, ref System.Data.DataTable DataUser, ref string StrError) {
            WebApplication1.LOGIN.ValidarHuellaRequest inValue = new WebApplication1.LOGIN.ValidarHuellaRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.pFMD = pFMD;
            inValue.DataUser = DataUser;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.ValidarHuellaResponse retVal = ((WebApplication1.LOGIN.IService)(this)).ValidarHuella(inValue);
            DataUser = retVal.DataUser;
            StrError = retVal.StrError;
            return retVal.ValidarHuellaResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.ValidarHuellaResponse> ValidarHuellaAsync(WebApplication1.LOGIN.ValidarHuellaRequest request) {
            return base.Channel.ValidarHuellaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.LOGIN.ValidarLoginResponse WebApplication1.LOGIN.IService.ValidarLogin(WebApplication1.LOGIN.ValidarLoginRequest request) {
            return base.Channel.ValidarLogin(request);
        }
        
        public bool ValidarLogin(string StrCodigo, string StrUsuario, string pwd_Login, ref System.Data.DataTable DataUser, ref string StrError) {
            WebApplication1.LOGIN.ValidarLoginRequest inValue = new WebApplication1.LOGIN.ValidarLoginRequest();
            inValue.StrCodigo = StrCodigo;
            inValue.StrUsuario = StrUsuario;
            inValue.pwd_Login = pwd_Login;
            inValue.DataUser = DataUser;
            inValue.StrError = StrError;
            WebApplication1.LOGIN.ValidarLoginResponse retVal = ((WebApplication1.LOGIN.IService)(this)).ValidarLogin(inValue);
            DataUser = retVal.DataUser;
            StrError = retVal.StrError;
            return retVal.ValidarLoginResult;
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LOGIN.ValidarLoginResponse> ValidarLoginAsync(WebApplication1.LOGIN.ValidarLoginRequest request) {
            return base.Channel.ValidarLoginAsync(request);
        }
    }
}
