//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.CREDENTIAL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CREDENTIAL.IWebRequest")]
    public interface IWebRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebRequest/GetResponse", ReplyAction="http://tempuri.org/IWebRequest/GetResponseResponse")]
        string GetResponse(string pXmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebRequest/GetResponse", ReplyAction="http://tempuri.org/IWebRequest/GetResponseResponse")]
        System.Threading.Tasks.Task<string> GetResponseAsync(string pXmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebRequestChannel : WebApplication1.CREDENTIAL.IWebRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebRequestClient : System.ServiceModel.ClientBase<WebApplication1.CREDENTIAL.IWebRequest>, WebApplication1.CREDENTIAL.IWebRequest {
        
        public WebRequestClient() {
        }
        
        public WebRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetResponse(string pXmlData) {
            return base.Channel.GetResponse(pXmlData);
        }
        
        public System.Threading.Tasks.Task<string> GetResponseAsync(string pXmlData) {
            return base.Channel.GetResponseAsync(pXmlData);
        }
    }
}
