//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.apache.org/ns/synapse", ConfigurationName="ServiceReference1.CASA_SRTMX_CuentaPortType")]
    public interface CASA_SRTMX_CuentaPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Desbloquear no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.output1 Desbloquear(WebApplication1.ServiceReference1.input1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output1> DesbloquearAsync(WebApplication1.ServiceReference1.input1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Bloquear no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.output2 Bloquear(WebApplication1.ServiceReference1.input2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output2> BloquearAsync(WebApplication1.ServiceReference1.input2 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Consultar no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.output3 Consultar(WebApplication1.ServiceReference1.input3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output3> ConsultarAsync(WebApplication1.ServiceReference1.input3 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación BloqDesbloqMasivo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.output4 BloqDesbloqMasivo(WebApplication1.ServiceReference1.input4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output4> BloqDesbloqMasivoAsync(WebApplication1.ServiceReference1.input4 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class DesbloquearRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Autenticacion autenticacionField;
        
        private Originador originadorField;
        
        private string cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Autenticacion Autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("Autenticacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Originador Originador {
            get {
                return this.originadorField;
            }
            set {
                this.originadorField = value;
                this.RaisePropertyChanged("Originador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ResultadoPedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuentaField;
        
        private Especificacion respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Especificacion Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Especificacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ResumenRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Especificacion respuestaField;
        
        private string cantidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Especificacion Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ResultadosProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResumenRespuesta[] resumenesField;
        
        private ResultadoPedido[] detallesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resumen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ResumenRespuesta[] Resumenes {
            get {
                return this.resumenesField;
            }
            set {
                this.resumenesField = value;
                this.RaisePropertyChanged("Resumenes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Pedido", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ResultadoPedido[] Detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
                this.RaisePropertyChanged("Detalles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Pedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuentaField;
        
        private string accionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("Accion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Liquidacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaVencimientoField;
        
        private string saldoField;
        
        private string pagoMinimoField;
        
        private string saldoDolarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("FechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PagoMinimo {
            get {
                return this.pagoMinimoField;
            }
            set {
                this.pagoMinimoField = value;
                this.RaisePropertyChanged("PagoMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SaldoDolar {
            get {
                return this.saldoDolarField;
            }
            set {
                this.saldoDolarField = value;
                this.RaisePropertyChanged("SaldoDolar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Importes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comprasField;
        
        private string cuotasField;
        
        private string adelantosField;
        
        private string prestamosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Compras {
            get {
                return this.comprasField;
            }
            set {
                this.comprasField = value;
                this.RaisePropertyChanged("Compras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Cuotas {
            get {
                return this.cuotasField;
            }
            set {
                this.cuotasField = value;
                this.RaisePropertyChanged("Cuotas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Adelantos {
            get {
                return this.adelantosField;
            }
            set {
                this.adelantosField = value;
                this.RaisePropertyChanged("Adelantos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Prestamos {
            get {
                return this.prestamosField;
            }
            set {
                this.prestamosField = value;
                this.RaisePropertyChanged("Prestamos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string momentoRenewalField;
        
        private string momentoUltimaActualizacionField;
        
        private string momentoUltimaOperacionAprobadaField;
        
        private string momentoUltimaOperacionDenegadaField;
        
        private string momentoUltimoBloqueoField;
        
        private string momentoUltimoDesbloqueoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MomentoRenewal {
            get {
                return this.momentoRenewalField;
            }
            set {
                this.momentoRenewalField = value;
                this.RaisePropertyChanged("MomentoRenewal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MomentoUltimaActualizacion {
            get {
                return this.momentoUltimaActualizacionField;
            }
            set {
                this.momentoUltimaActualizacionField = value;
                this.RaisePropertyChanged("MomentoUltimaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MomentoUltimaOperacionAprobada {
            get {
                return this.momentoUltimaOperacionAprobadaField;
            }
            set {
                this.momentoUltimaOperacionAprobadaField = value;
                this.RaisePropertyChanged("MomentoUltimaOperacionAprobada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MomentoUltimaOperacionDenegada {
            get {
                return this.momentoUltimaOperacionDenegadaField;
            }
            set {
                this.momentoUltimaOperacionDenegadaField = value;
                this.RaisePropertyChanged("MomentoUltimaOperacionDenegada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MomentoUltimoBloqueo {
            get {
                return this.momentoUltimoBloqueoField;
            }
            set {
                this.momentoUltimoBloqueoField = value;
                this.RaisePropertyChanged("MomentoUltimoBloqueo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MomentoUltimoDesbloqueo {
            get {
                return this.momentoUltimoDesbloqueoField;
            }
            set {
                this.momentoUltimoDesbloqueoField = value;
                this.RaisePropertyChanged("MomentoUltimoDesbloqueo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Indicadores : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vIPField;
        
        private string hCCField;
        
        private string uLCField;
        
        private string mCCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VIP {
            get {
                return this.vIPField;
            }
            set {
                this.vIPField = value;
                this.RaisePropertyChanged("VIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string HCC {
            get {
                return this.hCCField;
            }
            set {
                this.hCCField = value;
                this.RaisePropertyChanged("HCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ULC {
            get {
                return this.uLCField;
            }
            set {
                this.uLCField = value;
                this.RaisePropertyChanged("ULC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MCC {
            get {
                return this.mCCField;
            }
            set {
                this.mCCField = value;
                this.RaisePropertyChanged("MCC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class DetalleCuenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private Especificacion estadoField;
        
        private Especificacion entidadField;
        
        private string sucursalField;
        
        private Especificacion productoField;
        
        private Especificacion paisField;
        
        private Especificacion monedaField;
        
        private Indicadores indicadoresField;
        
        private Actividad actividadField;
        
        private Importes disponiblesField;
        
        private Importes limitesField;
        
        private Liquidacion liquidacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Especificacion Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Especificacion Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Especificacion Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("Producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Especificacion Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Especificacion Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Indicadores Indicadores {
            get {
                return this.indicadoresField;
            }
            set {
                this.indicadoresField = value;
                this.RaisePropertyChanged("Indicadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Actividad Actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("Actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public Importes Disponibles {
            get {
                return this.disponiblesField;
            }
            set {
                this.disponiblesField = value;
                this.RaisePropertyChanged("Disponibles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public Importes Limites {
            get {
                return this.limitesField;
            }
            set {
                this.limitesField = value;
                this.RaisePropertyChanged("Limites");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public Liquidacion Liquidacion {
            get {
                return this.liquidacionField;
            }
            set {
                this.liquidacionField = value;
                this.RaisePropertyChanged("Liquidacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Atencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inicioField;
        
        private string finField;
        
        private string tiempoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("Inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fin {
            get {
                return this.finField;
            }
            set {
                this.finField = value;
                this.RaisePropertyChanged("Fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Tiempo {
            get {
                return this.tiempoField;
            }
            set {
                this.tiempoField = value;
                this.RaisePropertyChanged("Tiempo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ResponseWS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string ticketWSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TicketWS {
            get {
                return this.ticketWSField;
            }
            set {
                this.ticketWSField = value;
                this.RaisePropertyChanged("TicketWS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apache.org/ns/synapse")]
    public partial class Originador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string solicitanteField;
        
        private string zonaHorariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Solicitante {
            get {
                return this.solicitanteField;
            }
            set {
                this.solicitanteField = value;
                this.RaisePropertyChanged("Solicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZonaHoraria {
            get {
                return this.zonaHorariaField;
            }
            set {
                this.zonaHorariaField = value;
                this.RaisePropertyChanged("ZonaHoraria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class DesbloquearResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWS responseField;
        
        private Atencion atencionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseWS Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Atencion Atencion {
            get {
                return this.atencionField;
            }
            set {
                this.atencionField = value;
                this.RaisePropertyChanged("Atencion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class input1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.DesbloquearRequest DesbloquearRequest;
        
        public input1() {
        }
        
        public input1(WebApplication1.ServiceReference1.DesbloquearRequest DesbloquearRequest) {
            this.DesbloquearRequest = DesbloquearRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class output1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.DesbloquearResponse DesbloquearResponse;
        
        public output1() {
        }
        
        public output1(WebApplication1.ServiceReference1.DesbloquearResponse DesbloquearResponse) {
            this.DesbloquearResponse = DesbloquearResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class BloquearRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Autenticacion autenticacionField;
        
        private Originador originadorField;
        
        private string cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Autenticacion Autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("Autenticacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Originador Originador {
            get {
                return this.originadorField;
            }
            set {
                this.originadorField = value;
                this.RaisePropertyChanged("Originador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class BloquearResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWS responseField;
        
        private Atencion atencionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseWS Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Atencion Atencion {
            get {
                return this.atencionField;
            }
            set {
                this.atencionField = value;
                this.RaisePropertyChanged("Atencion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class input2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.BloquearRequest BloquearRequest;
        
        public input2() {
        }
        
        public input2(WebApplication1.ServiceReference1.BloquearRequest BloquearRequest) {
            this.BloquearRequest = BloquearRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class output2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.BloquearResponse BloquearResponse;
        
        public output2() {
        }
        
        public output2(WebApplication1.ServiceReference1.BloquearResponse BloquearResponse) {
            this.BloquearResponse = BloquearResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ConsultarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Autenticacion autenticacionField;
        
        private Originador originadorField;
        
        private string cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Autenticacion Autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("Autenticacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Originador Originador {
            get {
                return this.originadorField;
            }
            set {
                this.originadorField = value;
                this.RaisePropertyChanged("Originador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class ConsultarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWS responseField;
        
        private Atencion atencionField;
        
        private DetalleCuenta cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseWS Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Atencion Atencion {
            get {
                return this.atencionField;
            }
            set {
                this.atencionField = value;
                this.RaisePropertyChanged("Atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DetalleCuenta Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class input3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.ConsultarRequest ConsultarRequest;
        
        public input3() {
        }
        
        public input3(WebApplication1.ServiceReference1.ConsultarRequest ConsultarRequest) {
            this.ConsultarRequest = ConsultarRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class output3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.ConsultarResponse ConsultarResponse;
        
        public output3() {
        }
        
        public output3(WebApplication1.ServiceReference1.ConsultarResponse ConsultarResponse) {
            this.ConsultarResponse = ConsultarResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class BloqDesbloqMasivoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Autenticacion autenticacionField;
        
        private Originador originadorField;
        
        private Pedido[] pedidosField;
        
        private string[] productosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Autenticacion Autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("Autenticacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Originador Originador {
            get {
                return this.originadorField;
            }
            set {
                this.originadorField = value;
                this.RaisePropertyChanged("Originador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Pedido[] Pedidos {
            get {
                return this.pedidosField;
            }
            set {
                this.pedidosField = value;
                this.RaisePropertyChanged("Pedidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Producto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] Productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("Productos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/ns/synapse")]
    public partial class BloqDesbloqMasivoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWS responseField;
        
        private Atencion atencionField;
        
        private ResultadosProceso resultadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseWS Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Atencion Atencion {
            get {
                return this.atencionField;
            }
            set {
                this.atencionField = value;
                this.RaisePropertyChanged("Atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ResultadosProceso Resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
                this.RaisePropertyChanged("Resultados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class input4 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.BloqDesbloqMasivoRequest BloqDesbloqMasivoRequest;
        
        public input4() {
        }
        
        public input4(WebApplication1.ServiceReference1.BloqDesbloqMasivoRequest BloqDesbloqMasivoRequest) {
            this.BloqDesbloqMasivoRequest = BloqDesbloqMasivoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class output4 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/ns/synapse", Order=0)]
        public WebApplication1.ServiceReference1.BloqDesbloqMasivoResponse BloqDesbloqMasivoResponse;
        
        public output4() {
        }
        
        public output4(WebApplication1.ServiceReference1.BloqDesbloqMasivoResponse BloqDesbloqMasivoResponse) {
            this.BloqDesbloqMasivoResponse = BloqDesbloqMasivoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CASA_SRTMX_CuentaPortTypeChannel : WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CASA_SRTMX_CuentaPortTypeClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType>, WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType {
        
        public CASA_SRTMX_CuentaPortTypeClient() {
        }
        
        public CASA_SRTMX_CuentaPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CASA_SRTMX_CuentaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASA_SRTMX_CuentaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASA_SRTMX_CuentaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.output1 WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.Desbloquear(WebApplication1.ServiceReference1.input1 request) {
            return base.Channel.Desbloquear(request);
        }
        
        public WebApplication1.ServiceReference1.DesbloquearResponse Desbloquear(WebApplication1.ServiceReference1.DesbloquearRequest DesbloquearRequest) {
            WebApplication1.ServiceReference1.input1 inValue = new WebApplication1.ServiceReference1.input1();
            inValue.DesbloquearRequest = DesbloquearRequest;
            WebApplication1.ServiceReference1.output1 retVal = ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).Desbloquear(inValue);
            return retVal.DesbloquearResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output1> WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.DesbloquearAsync(WebApplication1.ServiceReference1.input1 request) {
            return base.Channel.DesbloquearAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output1> DesbloquearAsync(WebApplication1.ServiceReference1.DesbloquearRequest DesbloquearRequest) {
            WebApplication1.ServiceReference1.input1 inValue = new WebApplication1.ServiceReference1.input1();
            inValue.DesbloquearRequest = DesbloquearRequest;
            return ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).DesbloquearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.output2 WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.Bloquear(WebApplication1.ServiceReference1.input2 request) {
            return base.Channel.Bloquear(request);
        }
        
        public WebApplication1.ServiceReference1.BloquearResponse Bloquear(WebApplication1.ServiceReference1.BloquearRequest BloquearRequest) {
            WebApplication1.ServiceReference1.input2 inValue = new WebApplication1.ServiceReference1.input2();
            inValue.BloquearRequest = BloquearRequest;
            WebApplication1.ServiceReference1.output2 retVal = ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).Bloquear(inValue);
            return retVal.BloquearResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output2> WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.BloquearAsync(WebApplication1.ServiceReference1.input2 request) {
            return base.Channel.BloquearAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output2> BloquearAsync(WebApplication1.ServiceReference1.BloquearRequest BloquearRequest) {
            WebApplication1.ServiceReference1.input2 inValue = new WebApplication1.ServiceReference1.input2();
            inValue.BloquearRequest = BloquearRequest;
            return ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).BloquearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.output3 WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.Consultar(WebApplication1.ServiceReference1.input3 request) {
            return base.Channel.Consultar(request);
        }
        
        public WebApplication1.ServiceReference1.ConsultarResponse Consultar(WebApplication1.ServiceReference1.ConsultarRequest ConsultarRequest) {
            WebApplication1.ServiceReference1.input3 inValue = new WebApplication1.ServiceReference1.input3();
            inValue.ConsultarRequest = ConsultarRequest;
            WebApplication1.ServiceReference1.output3 retVal = ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).Consultar(inValue);
            return retVal.ConsultarResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output3> WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.ConsultarAsync(WebApplication1.ServiceReference1.input3 request) {
            return base.Channel.ConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output3> ConsultarAsync(WebApplication1.ServiceReference1.ConsultarRequest ConsultarRequest) {
            WebApplication1.ServiceReference1.input3 inValue = new WebApplication1.ServiceReference1.input3();
            inValue.ConsultarRequest = ConsultarRequest;
            return ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).ConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.output4 WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.BloqDesbloqMasivo(WebApplication1.ServiceReference1.input4 request) {
            return base.Channel.BloqDesbloqMasivo(request);
        }
        
        public WebApplication1.ServiceReference1.BloqDesbloqMasivoResponse BloqDesbloqMasivo(WebApplication1.ServiceReference1.BloqDesbloqMasivoRequest BloqDesbloqMasivoRequest) {
            WebApplication1.ServiceReference1.input4 inValue = new WebApplication1.ServiceReference1.input4();
            inValue.BloqDesbloqMasivoRequest = BloqDesbloqMasivoRequest;
            WebApplication1.ServiceReference1.output4 retVal = ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).BloqDesbloqMasivo(inValue);
            return retVal.BloqDesbloqMasivoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output4> WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType.BloqDesbloqMasivoAsync(WebApplication1.ServiceReference1.input4 request) {
            return base.Channel.BloqDesbloqMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.output4> BloqDesbloqMasivoAsync(WebApplication1.ServiceReference1.BloqDesbloqMasivoRequest BloqDesbloqMasivoRequest) {
            WebApplication1.ServiceReference1.input4 inValue = new WebApplication1.ServiceReference1.input4();
            inValue.BloqDesbloqMasivoRequest = BloqDesbloqMasivoRequest;
            return ((WebApplication1.ServiceReference1.CASA_SRTMX_CuentaPortType)(this)).BloqDesbloqMasivoAsync(inValue);
        }
    }
}
